### ISSUE TITLE
Missing file pytorch_model.bin

### ISSUE THREAD

**Issue by ducanha2k46** [slptongji/MPEG#1]
FileNotFoundError: The pre-trained model path does not exist: models/RoBERTa/pytorch_model.bin.
Where can I find the above file

**Comment by Tim4Dec** [comment]
邮件已收到。

**Comment by Tim4Dec** [comment]
I'm sorry, I can't remember the link I downloaded this from : (. Maybe you can get it from huggingface, like https://huggingface.co/FacebookAI/roberta-large/tree/main.

**Comment by Tim4Dec** [comment]
I'm sorry : (, I can't remember the link where I downloaded this . Maybe you can get it from huggingface, like https://huggingface.co/FacebookAI/roberta-large/tree/main.

**Comment by ducanha2k46** [comment]
Thank you, I found and solved the problem.
